FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y tesseract-ocr libglib2.0-0 libsm6 libxrender1 libxext6 && \
    pip install --no-cache-dir streamlit pytesseract opencv-python Pillow googletrans==4.0.0-rc1

WORKDIR /app
COPY . /app

CMD ["streamlit", "run", "app.py", "--server.port=8080", "--server.enableCORS=false"]